name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem && chmod 600 ssh_key.pem

      - name: Get server username and IP
        run: |
          echo "SERVER_USERNAME=${{ secrets.SERVER_USERNAME }}"
          echo "SERVER_IP=${{ secrets.SERVER_IP }}"
          echo "SERVER_USERNAME=${{ secrets.SERVER_USERNAME }}" >> $GITHUB_ENV
          echo "SERVER_IP=${{ secrets.SERVER_IP }}" >> $GITHUB_ENV

      - name: Deploy to server
        run: |
          echo "Deploying to $SERVER_USERNAME@$SERVER_IP"
          ssh -v -o StrictHostKeyChecking=no -i ssh_key.pem $SERVER_USERNAME@$SERVER_IP "cd /home/ubuntu/dev-gabriel-alves/ && git pull origin main"
